version: 2
updates:
  - allow:
      - dependency-type: all
    commit-message:
      prefix: ci(actions)
    directory: /
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 5
    package-ecosystem: github-actions
    schedule:
      interval: weekly
  - allow:
      - dependency-type: all
    commit-message:
      prefix: ci(pre-commit)
    directory: /
    labels:
      - dependencies
    package-ecosystem: pre-commit
    schedule:
      interval: weekly
  - allow:
      - dependency-type: all
    commit-message:
      prefix: build(docker)
    directory: /docker
    labels:
      - dependencies
      - docker
    package-ecosystem: docker
    schedule:
      interval: weekly
  - allow:
      - dependency-type: all
    commit-message:
      prefix: build(npm)
    directory: /app
    groups:
      eslint:
        patterns:
          - '@eslint/*'
          - eslint
          - eslint-*
      framer-motion:
        patterns:
          - framer-motion
      i18n:
        patterns:
          - i18next
          - i18next-*
          - react-i18next
      react:
        patterns:
          - '@types/react*'
          - react
          - react-*
          - react-dom
      typescript:
        patterns:
          - '@types/*'
          - '@typescript-eslint/*'
          - typescript
      vite:
        patterns:
          - '@vitejs/*'
          - '@vitest/*'
          - vite
          - vitest
    labels:
      - dependencies
      - javascript
    open-pull-requests-limit: 10
    package-ecosystem: npm
    schedule:
      interval: weekly

    labels:
      - dependencies
      - pre-commit
