sonar.projectKey=chrysa_linkendin-resume
sonar.organization=chrysa
sonar.projectName=linkendin-resume

sonar.sources=app/src
sonar.tests=app/src/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/public/**,**/.vscode/**

sonar.typescript.tsconfigPath=app/tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**
sonar.cpd.exclusions=**
